---
output: html_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Note to author (delete before distribution)
```
git add --all 
git commit -m "name commit"
git push origin main
```

# familyenrollment

<!-- badges: start -->
<!-- badges: end -->

This package includes all functions used in data cleaning and estimation of "Household Bundling in Health Insurance". The latest version of the paper can be found here <https://www.andrew.cmu.edu/user/anhnguye/Household-Bundling.pdf>

## Installation
This package is not available on CRAN. To install this package, first navigate the directory to `familyenrollment`, then run `devtools::install()`. You will also need to load `library(tidyverse)` to use the pipe operator `%>%`.

## List of functions 

The functions used for estimation is stored in `R/base_functions.R`. Some of these functions are self explanatory, and hence their descriptions are skipped. 

### CARA\_fun\_Gauss  
This function computes the following integral using Gauss-Laguerre approximation: 
    \[
      \mathbb{E}\left[\frac{R^{1 - \omega} - 1}{1 - \omega}\right]
    \]
when $\omega \sim \mathcal{N}(\mu, \sigma^2)$ truncated at 0. 


### second_taylor_CARA
This function computes the following expectation w.r.t $U$ and $r$, where $r$ is a truncated normal distribution with mean $mu$ and standard deviation $\sigma$, and $U$ is uncorrelated with $r$. Let $\phi$ denote the standard normal distribution's pdf and $\Phi$ denote its CDF. 
\[
  \begin{align*}
    \mathbb{E}\left[ - \exp(-r U) \right] & \approx  \mathbb{E}\left[ - \exp(-r \mathbb{E}\left[U\right]) \right] +  \mathbb{E}\left[ - \frac{r^2}{2} \exp(-r \mathbb{E}\left[U\right]) \left(U - \mathbb{E}\left[U\right] \right)^2  \right] \\
    & = \left[ - \mathbb{E}\exp(-r \mathbb{E}\left[U\right]) \left(1 + \frac{r^2}{2} Var(U) \right) \right] \\
    & \propto - \int_0^{\infty} \exp(-r \mathbb{E}\left[U\right]) \left(1 + \frac{r^2}{2} Var(U) \right) \exp\left[-0.5 \frac{(r - \mu)^2}{\sigma^2} \right] \\
    & = -\exp \left(\frac{\sigma^2 (\mathbb{E} U)^2}{2} - \mu \mathbb{E} U  \right) \frac{1 - \Phi\left( -(\mu - a \sigma^2)/\sigma \right)}{1 - \Phi(-\mu/\sigma)} \\ 
    & \left[ 1 + \frac{Var(U)}{2} \left( \sigma^2  \left[1 - \frac{-\mu/\sigma \phi(-\mu/\sigma)}{1 - \Phi(-\mu/\sigma)} - \left(\phi(-\mu/\sigma)/(1 - \Phi(-\mu/\sigma))\right)^2 \right] + \left(\mu + \phi(-\mu/\sigma)/(1 - \Phi(-\mu/\sigma))\sigma \right)^2 \right) \right]
  \end{align*} 
\]

The arguments of `second_taylor_CARA` is `a`, which is $\mathbb{E}(U)$, `b`, which is $Var(U)$, and `mu` and `sigma`. 

### second_taylor_CARA_test
This function computes the numerical expectation of the function in `second_taylor_CARA`. 


### household_draw_theta_kappa_Rdraw_obsolete
Note: in this function, I use Gauss Hermite to approximate the expectation w.r.t $\bar{\theta}$. Note that Gauss Hermite is very accurate when the integral is over $X$, which is normally distributed with an unknown $\sigma$. However, the Hermite draws need to be normalized to center around the mean of the distribution of $X$. In addition, the Hermite draws are also scaled to have variance equal to the unconditional variance of each member's health shocks. 

First, draw (conditional) $\theta$ based on the unconditional distribution of $\theta$. Then, approximate the following integral, which is the expected utility conditional on health status $\bar{\theta}$, as 

\[
  \begin{align*}
    \int U(\pmb{\theta}, Y, \pmb{\kappa}) \exp(-1/2 (\log (\pmb{\theta} - \pmb{\bar{\theta}}) \sigma_{\pmb{\theta}}^{-2} \log (\pmb{\theta} - \pmb{\bar{\theta}})')) d\pmb{\theta}  \\
    \approx \mathbb{E}\left[ U(\pmb{\theta}, Y, \pmb{\kappa}) \exp(-1/2 (\log (\pmb{\theta} - \pmb{\bar{\theta}}) \sigma_{\theta|\pmb{\theta}}^{-2} \log (\pmb{\theta} - \pmb{\bar{\theta}})') + 1/2 \log(\pmb{\theta}) \sigma_{\theta}^{-2} \log(\pmb{\theta})')\right]
  \end{align*}
\]

where the expectation is taken over draws of $\theta$, drawn from the unconditional distribution. Note that this approximation works well when $\bar{\theta}$ is not too far from the unconditional mean because the variance of the <i>conditional</i> distribution is smaller than that of the unconditional distribution. 


The draws of $\bar{\theta}$ and their weights are stored in `Hermite_draw_mat` of the evaluated output. The draws of $\theta$  and coinsurance rates are stored in `theta_draw` and `kappa_draw`.

The computation of $\exp(-1/2 (\log (\pmb{\theta} - \pmb{\bar{\theta}}) \sigma_{\theta|\pmb{\bar{\theta}}}^{-2} \log (\pmb{\theta} - \pmb{\bar{\theta}})')$ requires knowing $\sigma_{\theta}$. So instead of computing this function directly, I use Taylor approximation around some $\sigma_0^2$
\[
    \exp(-1/2(x-\mu)^2/\sigma^2) =  \sum_{j = 0} \exp(-1/2(x-\mu)^2/\sigma_0^2) \frac{(-1/2(x-\mu)^2)^j}{j!}(\sigma^{-2} - \sigma_0^{-2})^j 
\] 
The issue with this function was that currently, the expected utility is taken also over $(\omega, \gamma, \delta)$, which is not correct. therefore, this function has been deemed obsolete. 

### household_draw_theta_kappa_Rdraw 
This function takes on data specific from each household, combines with `param`. This function draws $\theta$ based on Hermite draws. However, we use a transformed Hermite draws, $\theta = \verb|Hermite_draw| \times \sqrt{2} \times  \sigma_{\bar{\theta}}$. This is because the true $\sigma_{\theta}$ is strictly less than $\sigma_{\bar{\theta}}$, and the Hermite quadrature works better with this transformation. 

For each member's draws of $\theta$, also draw $\kappa$ if the person is insured. This function should produce a list, the first list is the draws of $\theta$, and the second list is the corresponding draws of $\kappa$.  

### compute_expected_U_m 
For this function, we are computing the expected value of 
\[
    U = \frac{R^{1-\omega} - 1}{1-\omega} - \sum \theta \delta \frac{(1 + \kappa)^{1-\gamma} - 1}{1 - \gamma}
\]
and 
\[
    OOP = \theta\kappa + \theta \kappa \delta R^{\omega} (1 + \kappa)^{-\gamma}
\]
where $\delta$ is truncated normal, $\gamma$ is also truncated normal, $\omega$ is truncated normal, and $\theta$ is log-normally distributed. The expectation of $m$ is over $\kappa, \delta, \omega, \theta$. The expectation w.r.t $\kappa, \delta, \omega$ have an analytical form (because of the truncated normal assumption). The expectation w.r.t $\theta$ cannot be done analytically because an insured individual has nonlinear $\kappa$. Therefore, for integration over $\theta$, we use numerical simulation with Halton draws.  


### identify_theta
This function uses the sample of households whose normalized income is negative; therefore, the observed medical expenses are the same as the health shocks. In this function, the health type draws $\bar{\theta}$ are Halton draws. I then compute $\mathbb{E}(\theta|\theta > 0)$, which has a closed form because it is the mean of a truncated normal distribution. Similarly, $\mathbb{E}(\theta^2|\theta > 0)$ is also computed. 

\[
    \mathbb{E}(\theta|\theta > 0) = \bar{\theta} + \frac{\phi(-\bar{\theta}/\sigma_{\theta})}{1 - \Phi(-\bar{\theta}/\sigma_{\theta})} \sigma_{\theta}
\]

\[
    \mathbb{E}(\theta^2|\theta > 0) = \left(\bar{\theta} + \frac{\phi(-\bar{\theta}/\sigma_{\theta})}{1 - \Phi(-\bar{\theta}/\sigma_{\theta})} \sigma_{\theta}\right)^2 + \sigma_{\theta}^2\left[1 + \frac{-\bar{\theta}/\sigma_{\theta} \phi(-\bar{\theta}/\sigma_{\theta}) }{1 - \Phi(-\bar{\theta}/\sigma_{\theta})} - \left(\frac{\phi(-\bar{\theta}/\sigma_{\theta})}{1 - \Phi(-\bar{\theta}/\sigma_{\theta})} \right)^2 \right]
\]

## Data objects 
 



